### PR TITLE
Update 1.0-Defining-a-Cloud-Strategy.

### PR DESCRIPTION
**Pull request by cxcod**

### CODE REVIEW

**Comment by cxcod** [comment]
Added content to the cloud Strategy section...

**Review by RonnieVogl — APPROVED** [review]
reviewed by Ronnie

**Review by RonnieVogl — APPROVED** [review]
reviewd by Ronnie

**Review by RonnieVogl — APPROVED** [review]
reviewed by Ronnie

**Review by RonnieVogl — APPROVED** [review]
reviewed by Ronnie

**Comment by RonnieVogl** [comment]
Ronnie merged commit

**Pull request merged**
